hotel_reservation/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from main.views import rooms,rooms_added,bookings,bookings_added,payments,payments_added,api,index,invoice
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name="index"),
    path('rooms/',rooms,name="rooms"),
    path('rooms_added/',rooms_added,name="rooms_added"),
    path('bookings/',bookings,name="bookings"),
    path('bookings_added/',bookings_added,name="bookings_added"),
    path('payments/',payments,name="payments"),
    path('payments_added/',payments_added,name="payments_added"),
    path('api/<id>',api,name="api"),
    path('invoice/<id>',invoice,name="invoice"),
]


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.
class test_data(models.Model):
    name = models.TextField()


class Payments(models.Model):
    paymentid = models.IntegerField(primary_key=True)
    bookingid = models.ForeignKey('Roombookings', models.DO_NOTHING, db_column='bookingid')
    paymenttype = models.CharField(max_length=255)
    paymentamount = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'payments'

    def __str__(self):
        return str(self.bookingid)




class Roombookings(models.Model):
    bookingid = models.IntegerField(primary_key=True)
    customername = models.CharField(max_length=500, blank=True, null=True)
    customeraddress = models.CharField(max_length=550, blank=True, null=True)
    bookingfrom = models.DateField(blank=True, null=True)
    bookingto = models.DateField(blank=True, null=True)
    assignroomid = models.ForeignKey('Rooms', models.DO_NOTHING, db_column='assignroomid', blank=True, null=True)
    noofguests = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'roombookings'

    def __str__(self):
        return str(self.customername)


class Rooms(models.Model):
    roomid = models.IntegerField(primary_key=True)
    roomnumber = models.IntegerField()
    roomprice = models.IntegerField()
    roomtype = models.CharField(max_length=255)
    roomcapacity = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'rooms'

    def __str__(self):
        return str(self.roomnumber)

main/forms.py
from django import forms
from .models import Rooms,Roombookings,Payments

class DateInput(forms.DateInput):
    input_type = 'date'

class RoomForm(forms.ModelForm):
    class Meta:
        model = Rooms
        fields = ['roomid','roomnumber','roomprice','roomtype','roomcapacity']
        labels = {'roomid':'roomid','roomnumber': "roomnumber", "roomprice": "Price",
                  'roomtype':'Type','roomcapacity':'Capacity'}
    # roomnumber = forms.IntegerField()
    # roomprice = forms.IntegerField()
    # roomtype = forms.CharField(max_length=255)
    # roomcapacity = forms.IntegerField()

class RoombookingsForm(forms.ModelForm):
    class Meta:
        model = Roombookings
        fields = ['bookingid', 'customername', 'customeraddress', 'bookingfrom', 'bookingto',
                  'assignroomid','noofguests']

        widgets = {
            'bookingfrom': DateInput(),
            'bookingto' : DateInput()
        }
        # labels = {'roomid': 'roomid', 'roomnumber': "roomnumber", "roomprice": "Price",
        #           'roomtype': 'Type', 'roomcapacity': 'Capacity'}

class PaymentsForm(forms.ModelForm):
    class Meta:
        model = Payments
        fields = ['paymentid','bookingid','paymenttype','paymentamount']

main/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from django.db import connection
from .forms import RoomForm,RoombookingsForm,PaymentsForm
from datetime import date
from .models import Rooms, Roombookings, Payments
# Create your views here.


def index(request):
    return render(request,"files/index.html")


def rooms(request):
    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            # roomnumber = room_form.cleaned_data['Room Number']
            # roomprice = room_form.cleaned_data['Room Price']
            # roomtype = room_form.cleaned_data['Room Type']
            # roomcapacity = room_form.cleaned_data['Room Capacity']
            form.save()
            return redirect('/rooms_added/')
    return render(request,'files/rooms.html',{'form': RoomForm()})

def rooms_added(request):

    return HttpResponse("Rooms Added Successfully")

def bookings(request):
    if request.method == 'POST':
        form = RoombookingsForm(request.POST)
        if form.is_valid():
            # roomnumber = room_form.cleaned_data['Room Number']
            # roomprice = room_form.cleaned_data['Room Price']
            # roomtype = room_form.cleaned_data['Room Type']
            # roomcapacity = room_form.cleaned_data['Room Capacity']
            form.save()
            return redirect('/bookings_added/')
    return render(request,'files/bookings.html',{'form': RoombookingsForm()})

def bookings_added(request):

    return HttpResponse("Bookings Added Successfully")

def payments(request):
    if request.method == 'POST':
        form = PaymentsForm(request.POST)
        if form.is_valid():
            # roomnumber = room_form.cleaned_data['Room Number']
            # roomprice = room_form.cleaned_data['Room Price']
            # roomtype = room_form.cleaned_data['Room Type']
            # roomcapacity = room_form.cleaned_data['Room Capacity']
            form.save()
            b_id = form.cleaned_data['bookingid']
            return redirect('/invoice/'+str(b_id))
    return render(request,'files/payments.html',{'form': PaymentsForm()})

def payments_added(request):

    return HttpResponse("Payments Done Successfully")

def api(request,id):
    def dictfetchall(cursor):
        "Return all rows from a cursor as a dict"
        columns = [col[0] for col in cursor.description]
        return [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]

    with connection.cursor() as cursor:
        cursor.execute('select bookingfrom,bookingto,roomprice from roombookings inner join rooms on assignroomid = roomid where bookingid = %s',[id])
        r = dictfetchall(cursor)
    price_list = []
    for i in r:
        d0 = i['bookingfrom']
        d1 = i['bookingto']
        delta = d1-d0
        price = i['roomprice'] * delta.days
        price_list.append(price)

    context = {}
    for i in price_list:
        context['total_price'] = i
    return JsonResponse(context)


def invoice(request,id):
    obj_1 = Roombookings.objects.filter(customername__icontains=id)
    obj_2 = Payments.objects.filter(bookingid__customername__icontains=id)
    context = {'obj_1':obj_1,'obj_2': obj_2}
    return render(request,"files/invoice.html",context)

templates/files/bookings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Bookings</title>
    <!-- CSS only -->
<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
<!--    &lt;!&ndash; JavaScript Bundle with Popper &ndash;&gt;-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>-->
<!--  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->
</head>
<body>
<form  action="" method="POST" >
    {% csrf_token %}
    {{form.as_p}}
<!--  <div class="form-row align-items-center">-->
<!--      <div class="col-auto">-->
<!--      <label class="sr-only" for="inlineFormInput">Room Id</label>-->
<!--      <input type="text" name = "RoomId" class="form-control mb-2" id="inlineFormInput" placeholder="Room Id">-->
<!--    </div>-->
<!--    <br>-->
<!--    <div class="col-auto">-->
<!--      <label class="sr-only" for="inlineFormInput">Room Number</label>-->
<!--      <input type="text" name = "RoomNumber" class="form-control mb-2" id="inlineFormInput" placeholder="Room No">-->
<!--    </div>-->
<!--    <br>-->
<!--    <div class="col-auto">-->
<!--      <label class="sr-only" for="inlineFormInputGroup">Room Type</label>-->
<!--   <input type="text" name = "RoomType" class="form-control mb-2" id="inlineFormInput" placeholder="Room Type">-->
<!--        </div>-->
<!--        <br>-->
<!--        <div class="col-auto">-->
<!--      <label class="sr-only" for="inlineFormInput">Room Price</label>-->
<!--      <input type="text" name ="RoomPrice" class="form-control mb-2" id="inlineFormInput" placeholder="Room Price">-->
<!--    </div>-->
<!--      <br>-->
<!--         <div class="col-auto">-->
<!--      <label class="sr-only" for="inlineFormInput">Room Capacity</label>-->
<!--      <input type="text" name ="RoomCapacity" class="form-control mb-2" id="inlineFormInput" placeholder="Room Capacity">-->
<!--    </div>-->

<!--      </div>-->
<!--    <br>-->



<!--&lt;!&ndash;    <div class="col-auto">&ndash;&gt;-->
<!--&lt;!&ndash;      <div class="form-check mb-2">&ndash;&gt;-->
<!--&lt;!&ndash;        <input class="form-check-input" type="checkbox" id="autoSizingCheck">&ndash;&gt;-->
<!--&lt;!&ndash;        <label class="form-check-label" for="autoSizingCheck">&ndash;&gt;-->
<!--&lt;!&ndash;          Remember me&ndash;&gt;-->
<!--&lt;!&ndash;        </label>&ndash;&gt;-->
<!--&lt;!&ndash;      </div>&ndash;&gt;-->
<!--&lt;!&ndash;    </div>&ndash;&gt;-->
   <input type = "submit" value ="Submit">

</form>


</body>
</html>

templates/files/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hotel Reservation App</title>
</head>
<body>

<h2><center>Hotel Reservation System</center></h2>
<center>
<h4><a href ="{% url 'rooms' %}">Add  Rooms</a></h4>

<h4><a href ="{% url 'bookings' %}">Add  Bookings</a></h4>

<h4><a href ="{% url 'payments' %}">Proceed To Payments</a></h4>
</center>
</body>
</html>

templates/files/invoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <style>
      #invoice{
    padding: 30px;
}

.invoice {
    position: relative;
    background-color: #FFF;
    min-height: 680px;
    padding: 15px
}

.invoice header {
    padding: 10px 0;
    margin-bottom: 20px;
    border-bottom: 1px solid #3989c6
}

.invoice .company-details {
    text-align: right
}

.invoice .company-details .name {
    margin-top: 0;
    margin-bottom: 0
}

.invoice .contacts {
    margin-bottom: 20px
}

.invoice .invoice-to {
    text-align: left
}

.invoice .invoice-to .to {
    margin-top: 0;
    margin-bottom: 0
}

.invoice .invoice-details {
    text-align: right
}

.invoice .invoice-details .invoice-id {
    margin-top: 0;
    color: #3989c6
}

.invoice main {
    padding-bottom: 50px
}

.invoice main .thanks {
    margin-top: -100px;
    font-size: 2em;
    margin-bottom: 50px
}

.invoice main .notices {
    padding-left: 6px;
    border-left: 6px solid #3989c6
}

.invoice main .notices .notice {
    font-size: 1.2em
}

.invoice table {
    width: 100%;
    border-collapse: collapse;
    border-spacing: 0;
    margin-bottom: 20px
}

.invoice table td,.invoice table th {
    padding: 15px;
    background: #eee;
    border-bottom: 1px solid #fff
}

.invoice table th {
    white-space: nowrap;
    font-weight: 400;
    font-size: 16px
}

.invoice table td h3 {
    margin: 0;
    font-weight: 400;
    color: #3989c6;
    font-size: 1.2em
}

.invoice table .qty,.invoice table .total,.invoice table .unit {
    text-align: right;
    font-size: 1.2em
}

.invoice table .no {
    color: #fff;
    font-size: 1.6em;
    background: #3989c6
}

.invoice table .unit {
    background: #ddd
}

.invoice table .total {
    background: #3989c6;
    color: #fff
}

.invoice table tbody tr:last-child td {
    border: none
}

.invoice table tfoot td {
    background: 0 0;
    border-bottom: none;
    white-space: nowrap;
    text-align: right;
    padding: 10px 20px;
    font-size: 1.2em;
    border-top: 1px solid #aaa
}

.invoice table tfoot tr:first-child td {
    border-top: none
}

.invoice table tfoot tr:last-child td {
    color: #3989c6;
    font-size: 1.4em;
    border-top: 1px solid #3989c6
}

.invoice table tfoot tr td:first-child {
    border: none
}

.invoice footer {
    width: 100%;
    text-align: center;
    color: #777;
    border-top: 1px solid #aaa;
    padding: 8px 0
}

@media print {
    .invoice {
        font-size: 11px!important;
        overflow: hidden!important
    }

    .invoice footer {
        position: absolute;
        bottom: 10px;
        page-break-after: always
    }

    .invoice>div:last-child {
        page-break-before: always
    }
}
    </style>
</head>
<body>
<div id="invoice">

    <div class="toolbar hidden-print">
        <div class="text-right">
            <button id="printInvoice" class="btn btn-info"><i class="fa fa-print"></i> Print</button>
            <button class="btn btn-info"><i class="fa fa-file-pdf-o"></i> Export as PDF</button>
        </div>
        <hr>
    </div>
    <div class="invoice overflow-auto">
        <div style="min-width: 600px">
            <header>
                <div class="row">
<!--                    <div class="col">-->
<!--                        <a target="_blank" href="https://lobianijs.com">-->
<!--                            <img src="http://lobianijs.com/lobiadmin/version/1.0/ajax/img/logo/lobiadmin-logo-text-64.png" data-holder-rendered="true" />-->
<!--                            </a>-->
<!--                    </div>-->
                    <div class="col company-details">
                        <h2 class="name">
                            <a target="_blank" href="https://lobianijs.com">
                            Hotel Name
                            </a>
                        </h2>
                        <div>Thamel,Kathmandu</div>
                        <div>(123) 456-789</div>
                        <div>company@example.com</div>
                    </div>
                </div>
            </header>
            <main>
                <div class="row contacts">
                    <div class="col invoice-to">
                        <div class="text-gray-light">INVOICE TO:</div>
                        {% for i in obj_1 %}
                        <h2 class="to">{{ i.customername }}</h2>
                        <div class="address">{{ i.customeraddress }}</div>
                        {% endfor %}

                    </div>
                    <div class="col invoice-details">
                        <h1 class="invoice-id">INVOICE </h1>
                        <div class="date">Date of Invoice: {% now "jS F Y" %}</div>

                    </div>
                </div>
                <table border="0" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th class="text-left">DESCRIPTION</th>
                            <th class="text-right">Room Rate</th>
<!--                            <th class="text-right">Nights</th>-->
                            <th class="text-right">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                       {% for i in obj_1 %}
                        <tr>
                            <td class="no">01</td>
                            <td class="text-left"><h3>
                                 {{ i.assignroomid.roomnumber }}
                                </h3>
                                <p>Booking from {{ i.bookingfrom }} to {{ i.bookingto }}</p>

                            </td>
                            <td class="unit">NPR {{ i.assignroomid.roomprice }}</td>
                            {% endfor %}
                            {% for i in obj_2 %}
<!--                            <td class="qty">100</td>-->
                            <td class="total">NPR {{ i.paymentamount }}</td>

                        </tr>
<!--                        <tr>-->
<!--                            <td class="no">01</td>-->
<!--                            <td class="text-left"><h3>Website Design</h3>Creating a recognizable design solution based on the company's existing visual identity</td>-->
<!--                            <td class="unit">$40.00</td>-->
<!--                            <td class="qty">30</td>-->
<!--                            <td class="total">$1,200.00</td>-->
<!--                        </tr>-->
<!--                        <tr>-->
<!--                            <td class="no">02</td>-->
<!--                            <td class="text-left"><h3>Website Development</h3>Developing a Content Management System-based Website</td>-->
<!--                            <td class="unit">$40.00</td>-->
<!--                            <td class="qty">80</td>-->
<!--                            <td class="total">$3,200.00</td>-->
<!--                        </tr>-->
<!--                        <tr>-->
<!--                            <td class="no">03</td>-->
<!--                            <td class="text-left"><h3>Search Engines Optimization</h3>Optimize the site for search engines (SEO)</td>-->
<!--                            <td class="unit">$40.00</td>-->
<!--                            <td class="qty">20</td>-->
<!--                            <td class="total">$800.00</td>-->
<!--                        </tr>-->
                    </tbody>
                    <tfoot>
<!--                        <tr>-->
<!--                            <td colspan="2"></td>-->
<!--                            <td colspan="2">SUBTOTAL</td>-->
<!--                            <td>$5,200.00</td>-->
<!--                        </tr>-->
<!--                        <tr>-->
<!--                            <td colspan="2"></td>-->
<!--                            <td colspan="2">TAX 25%</td>-->
<!--                            <td>$1,300.00</td>-->
<!--                        </tr>-->
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2">GRAND TOTAL</td>
                            <td>NPR {{ i.paymentamount }}</td>
                        </tr>
                    {% endfor %}
                    </tfoot>
                </table>
<!--                <div class="thanks">Thank you!</div>-->
<!--                <div class="notices">-->
<!--                    <div>NOTICE:</div>-->
<!--                    <div class="notice">A finance charge of 1.5% will be made on unpaid balances after 30 days.</div>-->
<!--                </div>-->
            </main>
            <footer>
                Invoice was created on a computer and is valid without the signature and seal.
            </footer>
        </div>
        <!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->
        <div></div>
    </div>
</div>

<script>
     $('#printInvoice').click(function(){
            Popup($('.invoice')[0].outerHTML);
            function Popup(data)
            {
                window.print();
                return true;
            }
        });
</script>

</body>
</html>

templates/files/payments.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Payments</title>
    <!-- CSS only -->
<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
<!--    &lt;!&ndash; JavaScript Bundle with Popper &ndash;&gt;-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->
</head>
<body>
<form  action="" method="POST" >
    {% csrf_token %}
    {{form.as_p}}
<!--  <div class="form-row align-items-center">-->
<!--      <div class="col-auto">-->
<!--      <label class="sr-only" for="inlineFormInput">Room Id</label>-->
<!--      <input type="text" name = "RoomId" class="form-control mb-2" id="inlineFormInput" placeholder="Room Id">-->
<!--    </div>-->
<!--    <br>-->
<!--    <div class="col-auto">-->
<!--      <label class="sr-only" for="inlineFormInput">Room Number</label>-->
<!--      <input type="text" name = "RoomNumber" class="form-control mb-2" id="inlineFormInput" placeholder="Room No">-->
<!--    </div>-->
<!--    <br>-->
<!--    <div class="col-auto">-->
<!--      <label class="sr-only" for="inlineFormInputGroup">Room Type</label>-->
<!--   <input type="text" name = "RoomType" class="form-control mb-2" id="inlineFormInput" placeholder="Room Type">-->
<!--        </div>-->
<!--        <br>-->
<!--        <div class="col-auto">-->
<!--      <label class="sr-only" for="inlineFormInput">Room Price</label>-->
<!--      <input type="text" name ="RoomPrice" class="form-control mb-2" id="inlineFormInput" placeholder="Room Price">-->
<!--    </div>-->
<!--      <br>-->
<!--         <div class="col-auto">-->
<!--      <label class="sr-only" for="inlineFormInput">Room Capacity</label>-->
<!--      <input type="text" name ="RoomCapacity" class="form-control mb-2" id="inlineFormInput" placeholder="Room Capacity">-->
<!--    </div>-->

<!--      </div>-->
<!--    <br>-->



<!--&lt;!&ndash;    <div class="col-auto">&ndash;&gt;-->
<!--&lt;!&ndash;      <div class="form-check mb-2">&ndash;&gt;-->
<!--&lt;!&ndash;        <input class="form-check-input" type="checkbox" id="autoSizingCheck">&ndash;&gt;-->
<!--&lt;!&ndash;        <label class="form-check-label" for="autoSizingCheck">&ndash;&gt;-->
<!--&lt;!&ndash;          Remember me&ndash;&gt;-->
<!--&lt;!&ndash;        </label>&ndash;&gt;-->
<!--&lt;!&ndash;      </div>&ndash;&gt;-->
<!--&lt;!&ndash;    </div>&ndash;&gt;-->
    <input type = "submit" value ="Generate Invoice" >

</form>

<script>
    $(document).ready(function($){
        $('#id_bookingid').on("change",function(){
            id = this.value
            $.ajax({
                type: 'get',
                url:'http://localhost:8000/api/'+id,
                success: function(response){
                    console.log(response.total_price)
                    $('#id_paymentamount').val(response.total_price)
                    }
                })
            })
        })
</script>
</body>
</html>

templates/files/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


{{ total_price }}

</body>
</html>